### ISSUE TITLE
I have file from iphone where it failed

### ISSUE THREAD

**Issue by vladobb** [ianare/exif-py#203]
how to proceed on? do you want me to send you file?

Z:\TW22Pycharm\.venv\Scripts\python.exe "Z:\TW22Pycharm\FilesAndFolders\2024-09-28 Exif.py" 
Traceback (most recent call last):
  File "Z:\TW22Pycharm\.venv\Lib\site-packages\exifread\heic.py", line 171, in get_parser
    return defs[box.name]
           ~~~~^^^^^^^^^^
KeyError: 'hdlr'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Z:\TW22Pycharm\FilesAndFolders\2024-09-28 Exif.py", line 10, in <module>
    tags = exifread.process_file(file_handle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\TW22Pycharm\.venv\Lib\site-packages\exifread\__init__.py", line 137, in process_file
    offset, endian, fake_exif = _determine_type(fh)
                                ^^^^^^^^^^^^^^^^^^^
  File "Z:\TW22Pycharm\.venv\Lib\site-packages\exifread\__init__.py", line 109, in _determine_type
    offset, endian = heic.find_exif()
                     ^^^^^^^^^^^^^^^^
  File "Z:\TW22Pycharm\.venv\Lib\site-packages\exifread\heic.py", line 268, in find_exif
    meta = self.expect_parse('meta')
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\TW22Pycharm\.venv\Lib\site-packages\exifread\heic.py", line 159, in expect_parse
    return self.parse_box(box)
           ^^^^^^^^^^^^^^^^^^^
  File "Z:\TW22Pycharm\.venv\Lib\site-packages\exifread\heic.py", line 177, in parse_box
    probe(box)
  File "Z:\TW22Pycharm\.venv\Lib\site-packages\exifread\heic.py", line 195, in _parse_meta
    psub = self.get_parser(box)
           ^^^^^^^^^^^^^^^^^^^^
  File "Z:\TW22Pycharm\.venv\Lib\site-packages\exifread\heic.py", line 173, in get_parser
    raise NoParser(box.name) from err
exifread.heic.NoParser: hdlr

Process finished with exit code 1

**Comment by vladobb** [comment]
adding file you can test on
[IMG_4386.ZIP](https://github.com/user-attachments/files/17175731/IMG_4386.ZIP)

**Comment by timrolsh** [comment]
same issue is happening to me
