### ISSUE TITLE
Problem with some JPEG files from Olympus PEN

### ISSUE THREAD

**Issue by michal-niklas** [ianare/exif-py#42]
Hello,

I use this libarary to rename/redate some JPEG file from various cameras just like in my recipe: http://code.activestate.com/recipes/550811-jpg-files-redater-by-exif-data/ (of course now I use `exifread` instead of `EXIF`). It works well with photos from my Canon camera but with some photos from Olympus camera it raises exception:

	Exception: <type 'exceptions.IndexError'>: string index out of range
	Traceback (most recent call last):
	  File "c:\tools\pyscripts\scripts\exif_redater.py", line 60, in redate_by_exif
	    tags = exifread.process_file(f)
	  File "C:\Python27\lib\site-packages\exifread\__init__.py", line 221, in process_file
	    hdr.decode_maker_note()
	  File "C:\Python27\lib\site-packages\exifread\classes.py", line 392, in decode_maker_note
	    tag_dict=makernote.OLYMPUS)
	  File "C:\Python27\lib\site-packages\exifread\classes.py", line 229, in dump_IFD
	    printable = tag_entry[1](values)
	  File "C:\Python27\lib\site-packages\exifread\tags\makernote.py", line 256, in olympus_special_mode
	    if v[0] not in mode1 or v[2] not in mode2:
	IndexError: string index out of range

I will try to attach such file but is is quite big (almost 3MiB) and I don't know if github changes it. It gives such SHA1 sum:

    1107a75242c828b8e9cae8f25d18134cc9877ce2 *P8237937.JPG

![p8237937](https://cloud.githubusercontent.com/assets/9588654/5332812/a0f0aab0-7e63-11e4-938e-b3267cb7271f.JPG)

**Comment by ianare** [comment]
Sorry for the delay. I was not able to get the proper info from the Maekernote, but at least now the lib doesn't crash.

Please let me know if it works better for you. Thanks!
